# Graphics
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2

# Menu Button Settings
BUTTON_LEFT = SCREEN_WIDTH / 2 - 70
BUTTON_TOP = SCREEN_HEIGHT / 2 - 100
BUTTON_WIDTH = 140
BUTTON_HEIGHT = 50


int(SCREEN_WIDTH / 2 - 70),
int((SCREEN_HEIGHT + 25) / 2 - 25),

# Player Settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Scoring
SCORE_INCREMENT = 10


# Bullets
SHOT_RADIUS = 5

# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
